Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20221029183410_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Hey Ricky, I think I did a pretty good job here, be nice please
=> Finished installing deviser for users

app/models/credit_card.rb, app/models/reservation.rb, app/models/user.rb, db/migrate/20221029185905_create_reservations.rb, db/schema.rb, test/models/reservation_test.rb
=> Made the reservations model and relations between models

app/controllers/credit_cards_controller.rb, app/views/credit_cards/index.html.erb, app/views/credit_cards/show.html.erb, config/routes.rb, test/controllers/credit_cards_controller_test.rb
I created the CC routes, controller actions (index/show) so far, and completed views
=> Creating cc controller

Gemfile, Gemfile.lock, db/seeds.rb
added faker gem, and seed details.
=> created user seed with faker

db/seeds.rb
added credit seeding using Faker
=> added CC seeding

app/views/credit_cards/show.html.erb, db/seeds.rb
Made corrections to syntax in seed and show files.
=> finished up syntax fixes

app/controllers/application_controller.rb, app/controllers/credit_cards_controller.rb, app/views/credit_cards/_form.html.erb, app/views/credit_cards/index.html.erb, app/views/credit_cards/new.html.erb
Completed addition of new actions (new/create) in CC controller, partial view for form (new), views for new/create and views.
Everything works now.
=> Adding CC feature

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
This PR adds a first version for the footer as a css component and partial.
=> Pages footer

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Added container and box classes to each form, and the bootstrap button classes so we can see the buttons.
=> Added boostrap classes to devise forms

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_card_home_page.scss, app/assets/stylesheets/components/_index.scss, app/views/credit_cards/_button.html.erb, app/views/credit_cards/_card.html.erb, app/views/credit_cards/_card_home_page.erb
I added two card components and their css as partials:
One for home page
Another for index
=> Card component

app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb
Just some flashes to fix the ugly alerts that we had
=> Added flashes styling to the app

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_home.scss, app/views/credit_cards/_card_home_page.erb
changed css for button using scss
=> Button part two

app/models/credit_card.rb, app/views/credit_cards/_form.html.erb, db/seeds.rb
I added a drop-down with list of approved issuers (see screenshot)
=> added issuers drop down

app/models/credit_card.rb, app/views/credit_cards/_form.html.erb, db/seeds.rb
I added card type drop down (see screenshot below):
=> added card type drop down

app/assets/stylesheets/components/_footer.scss
This PR adds the styling to make the footer fixed at the bottom
=> Added styles for fixed footer

app/controllers/reservations_controller.rb, app/views/reservations/show.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> My reservations page, linking to the card which was reserved

app/views/credit_cards/show.html.erb
fixed how cancel button is displayed.
=> fixed cancel button

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_index.scss, app/views/credit_cards/_card.html.erb, app/views/credit_cards/index.html.erb
=> Index page styling

app/views/shared/_navbar.html.erb
=> fixed navbar dropdown

app/views/credit_cards/my_cards.html.erb
=> My cards styling

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss
Added shadows to footer and navbar, and fixed the navbar to the top.
=> Fixed navbar

app/controllers/reservations_controller.rb, app/views/credit_cards/show.html.erb, app/views/reservations/edit.html.erb, config/routes.rb
1) added button for edit reservation
2) added form that takes current inputs and asks you to enter new dates
3) updates reservation when you press update
=> Adding edit reservation

app/controllers/credit_cards_controller.rb, app/views/credit_cards/edit.html.erb, app/views/credit_cards/show.html.erb
Now owner can edit card information
=> added edit owner card

app/assets/stylesheets/pages/_index.scss, app/views/credit_cards/index.html.erb
Added a div with a class in order to make buttons from the sidebar sticky
=> Added sticky property to index buttons

app/views/reservations/new.html.erb
=> Styled the reservations page

app/assets/stylesheets/components/_card.scss, app/views/credit_cards/_card.html.erb, app/views/credit_cards/index.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
made price per day in seeds from 20-100 ($)
Browse cards in the navbar instead of Rent a Card Now!
Card image overlays were added to make everything consistent.
Adding line to specify that we can filter by card types.
=> Heroku improvements

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/shared/_navbar.html.erb
Added the edit my profile link and option to upload a photo, so we can update Ricky's user on Saturday. Tested in my local and it updated my pic successfully 😄 
I also added a condition to show the icon when there's no photo yet, because it was breaking everything for me.
=> Add image to edit profile and link

app/views/credit_cards/show.html.erb, app/views/devise/registrations/edit.html.erb
=> minimized the appearance of the edit profile page

app/views/credit_cards/show.html.erb
=> Showing user who reserved the card in the reservations area

app/views/credit_cards/show.html.erb
=> Moved the user to the reservation's list group

app/views/reservations/show.html.erb
=> Add styling and edit button to my reservations
